version: '3.7'

services:

  db:
    build: 
      context: mysql
    container_name: db
    restart: always
    tty: true    
    volumes:
      - ./mysql/db:/var/lib/minesql 
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root            
    networks:
      - fullcycle-network

  node:
    build: 
      context: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh node index.js
    restart: always        
    tty: true          
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - fullcycle-network
    
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    restart: always    
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - fullcycle-network
  
networks:
  fullcycle-network:
    driver: bridge
    

