version: '3.7'

services:

  db:
    build: 
      context: mysql
    container_name: db
    restart: always
    tty: true    
    volumes:
      - ./mysql/db:/var/lib/minesql 
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root            
    networks:
      - fullcyle-network

  node:
    build: 
      context: ./node
    container_name: node
    restart: always        
    tty: true        
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db
    networks:
      - fullcyle-network
    
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    restart: always    
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - fullcyle-network
  
networks:
  fullcyle-network:
    driver: bridge
    

