version: '3.7'

services:

  db:
    image: fabiostefani/fullcycle-mysql:latest
    container_name: db
    restart: always
    tty: true    
    volumes:
      - ./mysql/db:/var/lib/minesql 
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root            
    networks:
      - fullcyle-network

  node:
    image: fabiostefani/fullcycle-nodeapp:latest
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh node index.js
    restart: always      
    tty: true        
    depends_on:
      - db
    networks:
      - fullcyle-network
    volumes:
      - /usr/src/app/node_modules
    
  nginx:
    image: fabiostefani/fullcycle-nginxapp:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - fullcyle-network    
  
networks:
  fullcyle-network:
    driver: bridge
    

